# Generated by Django 4.2.7 on 2025-11-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título (H1)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL amigable')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('hero_image', models.ImageField(help_text='Imagen principal del post', upload_to='blog/hero/', verbose_name='Imagen Hero')),
                ('problem_section', models.TextField(help_text='Descripción del problema que resuelve', verbose_name='Problema')),
                ('problem_image', models.ImageField(blank=True, null=True, upload_to='blog/problem/', verbose_name='Imagen Problema')),
                ('why_automate_section', models.TextField(help_text='Explicación de por qué automatizar', verbose_name='Por qué automatizar')),
                ('sales_angle_section', models.TextField(help_text='Punto de venta único', verbose_name='Ángulo de venta')),
                ('how_it_works_section', models.TextField(help_text='Explicación técnica del funcionamiento', verbose_name='Cómo funciona')),
                ('agent_diagram_image', models.ImageField(help_text='Imagen del diagrama del agente', upload_to='blog/diagram/', verbose_name='Diagrama del Agente')),
                ('benefits_section', models.TextField(help_text='Lista o descripción de beneficios', verbose_name='Beneficios')),
                ('hypothetical_case_section', models.TextField(help_text='Ejemplo hipotético de uso', verbose_name='Caso hipotético')),
                ('case_image', models.ImageField(blank=True, null=True, upload_to='blog/case/', verbose_name='Imagen Caso/Historia')),
                ('final_cta_section', models.TextField(help_text='Llamado a la acción final', verbose_name='CTA Final')),
                ('optional_icon_image', models.ImageField(blank=True, null=True, upload_to='blog/icon/', verbose_name='Imagen Icono (opcional)')),
                ('excerpt', models.TextField(help_text='Para mostrar en listados y SEO', max_length=300, verbose_name='Resumen breve')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta descripción')),
                ('category', models.CharField(choices=[('guias', 'Guías y buenas prácticas'), ('casos', 'Casos de uso'), ('faq', 'Preguntas frecuentes')], default='guias', max_length=20, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Entrada del Blog',
                'verbose_name_plural': 'Entradas del Blog',
                'ordering': ['-published_date'],
            },
        ),
    ]
