# Generated by Django 4.2.7 on 2025-11-16 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para la clave API', max_length=100, verbose_name='Nombre')),
                ('key', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Clave API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clave API',
                'verbose_name_plural': 'Claves API',
            },
        ),
    ]
