# Generated by Django 4.2.7 on 2025-11-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='agent_diagram_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='case_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='optional_icon_image',
        ),
    ]
