# Generated by Django 4.2.7 on 2025-11-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpost_agent_diagram_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen principal', verbose_name='Imagen Hero (URL)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='problem_image_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen del problema', verbose_name='Imagen Problema (URL)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Subir archivo de imagen o usar URL abajo', null=True, upload_to='blog/hero/', verbose_name='Imagen Hero (Archivo)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='problem_image',
            field=models.ImageField(blank=True, help_text='Subir archivo de imagen o usar URL abajo', null=True, upload_to='blog/problem/', verbose_name='Imagen Problema (Archivo)'),
        ),
    ]
