# Generated by Django 4.2.7 on 2025-09-10 01:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que pueden acceder al agente aunque no sea público en Agents o Solutions.', related_name='allowed_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='show_in_agents',
            field=models.BooleanField(default=True, help_text='Si está activo, aparece en el listado de Agents.'),
        ),
        migrations.AddField(
            model_name='agent',
            name='show_in_solutions',
            field=models.BooleanField(default=True, help_text='Si está activo, aparece en el listado público de Solutions.'),
        ),
    ]
