# Generated by Django 4.2.7 on 2025-09-12 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_allowed_users_agent_show_in_agents_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentconfiguration',
            options={'verbose_name': 'Configuración de agente', 'verbose_name_plural': 'Configuraciones de agentes'},
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_providers',
            field=models.BooleanField(default=False, help_text='Permitir a los usuarios gestionar proveedores para este agente', verbose_name='Habilitar gestión de proveedores'),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del proveedor')),
                ('phone', models.CharField(max_length=20, verbose_name='Número de teléfono')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='agents.agentconfiguration', verbose_name='Configuración del agente')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
    ]
