# Generated by Django 4.2.7 on 2025-09-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agentconfiguration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_categories', to='agents.agentconfiguration', verbose_name='Configuración del agente')),
            ],
            options={
                'verbose_name': 'Categoría de proveedor',
                'verbose_name_plural': 'Categorías de proveedores',
                'ordering': ['name'],
                'unique_together': {('name', 'agent_config')},
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='agents.providercategory', verbose_name='Categoría'),
        ),
    ]
