# Generated by Django 4.2.7 on 2025-09-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_providercategory_provider_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la marca')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='agents.agentconfiguration', verbose_name='Configuración del agente')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
                'unique_together': {('name', 'agent_config')},
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='providers', to='agents.brand', verbose_name='Marcas que maneja'),
        ),
    ]
