# Generated by Django 4.2.7 on 2025-10-14 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_brand_provider_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_products',
            field=models.BooleanField(default=False, help_text='Permitir a los usuarios gestionar productos para este agente', verbose_name='Habilitar gestión de productos'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del producto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen del producto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='agents.agentconfiguration', verbose_name='Configuración del agente')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
