# Generated by Django 4.2.7 on 2025-10-14 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_remove_product_brands_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_automotive_info',
            field=models.BooleanField(default=False, help_text='Permitir a los usuarios configurar información del centro automotriz para este agente', verbose_name='Habilitar información del centro automotriz'),
        ),
        migrations.CreateModel(
            name='AutomotiveCenterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_address', models.TextField(verbose_name='Dirección física del taller')),
                ('business_hours', models.JSONField(default=dict, help_text='Horarios de atención en formato JSON', verbose_name='Horarios de atención')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automotive_center_info', to='agents.agentconfiguration', verbose_name='Configuración del agente')),
            ],
            options={
                'verbose_name': 'Información del Centro Automotriz',
                'verbose_name_plural': 'Información de Centros Automotrices',
            },
        ),
    ]
