# Generated by Django 4.2.7 on 2025-10-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agentconfiguration_enable_automotive_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_upload_method',
            field=models.CharField(choices=[('file', 'Subir archivo'), ('url', 'Desde URL')], default='file', max_length=10, verbose_name='Método de carga de imagen'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la imagen'),
        ),
    ]
