# Generated by Django 4.2.7 on 2025-11-15 17:30

from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_add_json_gin_indexes'),
    ]

    operations = [
        # Create pg_trgm extension for trigram searches
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;"
        ),

        # MEDIUM-004: Añadir índices para búsquedas frecuentes
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['name'], name='idx_agent_name_search'),
        ),

        migrations.AddIndex(
            model_name='agentcategory',
            index=models.Index(fields=['name'], name='idx_agentcategory_name'),
        ),

        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='idx_product_title_search'),
        ),

        migrations.AddIndex(
            model_name='product',
            index=GinIndex(
                fields=['description'],
                name='idx_product_description_search',
                opclasses=['gin_trgm_ops']
            ),
        ),

        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['name'], name='idx_provider_name_search'),
        ),

        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['city'], name='idx_provider_city'),
        ),

        # Índices para campos JSONField con GIN
        migrations.AddIndex(
            model_name='agent',
            index=GinIndex(
                fields=['features'],
                name='idx_agent_features_gin',
                opclasses=['jsonb_path_ops']
            ),
        ),

        migrations.AddIndex(
            model_name='agentconfiguration',
            index=GinIndex(
                fields=['configuration_data'],
                name='idx_agentconfig_data_gin',
                opclasses=['jsonb_path_ops']
            ),
        ),

        # Índices para búsquedas de texto completo en español
        # TEMPORARILY COMMENTED: Index with ArrayField expression causes ValueError
        # See Django issue: Index.opclasses cannot be used with expressions
        # migrations.AddIndex(
        #     model_name='agent',
        #     index=GinIndex(
        #         django.contrib.postgres.fields.ArrayField(models.CharField(max_length=200)),
        #         name='idx_agent_text_search',
        #         opclasses=['gin_trgm_ops']
        #     ),
        # ),
    ]