# Generated by Django 4.2.7 on 2025-11-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agent',
            name='idx_agent_name_search',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='idx_agent_features_gin',
        ),
        migrations.RemoveIndex(
            model_name='agentcategory',
            name='idx_agentcategory_name',
        ),
        migrations.RemoveIndex(
            model_name='agentconfiguration',
            name='agent_config_data_gin',
        ),
        migrations.RemoveIndex(
            model_name='agentconfiguration',
            name='idx_agentconfig_data_gin',
        ),
        migrations.RemoveIndex(
            model_name='automotivecenterinfo',
            name='auto_center_hours_gin',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_product_title_search',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_product_description_search',
        ),
        migrations.RemoveIndex(
            model_name='provider',
            name='agents_prov_agent_co_12345_idx',
        ),
        migrations.RemoveIndex(
            model_name='provider',
            name='agents_prov_agent_co_67890_idx',
        ),
        migrations.RemoveIndex(
            model_name='provider',
            name='agents_provider_category_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='provider',
            name='idx_provider_name_search',
        ),
        migrations.RemoveIndex(
            model_name='provider',
            name='idx_provider_city',
        ),
        migrations.RenameIndex(
            model_name='agentconfiguration',
            new_name='agents_agen_user_id_e5c975_idx',
            old_name='agents_agen_user_age_12345_idx',
        ),
        migrations.RenameIndex(
            model_name='agentusagelog',
            new_name='agents_agen_executi_dc0d47_idx',
            old_name='agents_agent_execution_12345_idx',
        ),
        migrations.RenameIndex(
            model_name='brand',
            new_name='agents_bran_agent_c_a304bc_idx',
            old_name='agents_brand_agent_co_12345_idx',
        ),
        migrations.RenameIndex(
            model_name='productbrand',
            new_name='agents_prod_agent_c_caaafc_idx',
            old_name='agents_prod_agent_co_12345_idx',
        ),
        migrations.RenameIndex(
            model_name='productcategory',
            new_name='agents_prod_agent_c_7eaa83_idx',
            old_name='agents_prod_agent_co_67890_idx',
        ),
        migrations.RenameIndex(
            model_name='providercategory',
            new_name='agents_prov_agent_c_d2494f_idx',
            old_name='agents_prov_agent_co_99999_idx',
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['is_active', 'show_in_agents'], name='agents_agen_is_acti_5685d3_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['is_active', 'show_in_solutions'], name='agents_agen_is_acti_a4e95f_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['category', 'is_active'], name='agents_agen_categor_1edc19_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['created_at'], name='agents_agen_created_fa314f_idx'),
        ),
        migrations.AddIndex(
            model_name='agentusagelog',
            index=models.Index(fields=['user', 'agent', 'created_at'], name='agents_agen_user_id_e4dfc5_idx'),
        ),
        migrations.AddIndex(
            model_name='agentusagelog',
            index=models.Index(fields=['agent', 'created_at'], name='agents_agen_agent_i_2e60a1_idx'),
        ),
        migrations.AddIndex(
            model_name='agentusagelog',
            index=models.Index(fields=['success', 'created_at'], name='agents_agen_success_bfe2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='agentusagelog',
            index=models.Index(fields=['created_at'], name='agents_agen_created_c0153a_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='agents_user_user_id_a898ef_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['agent', 'status'], name='agents_user_agent_i_38006b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'end_date'], name='agents_user_status_38d41e_idx'),
        ),
    ]
