# Generated by Django 4.2.7 on 2025-12-03 22:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_remove_agent_idx_agent_name_search_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedCatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de catálogo avanzado',
                'verbose_name_plural': 'Categorías de catálogo avanzado',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_advanced_catalog',
            field=models.BooleanField(default=False, help_text='Permitir a los usuarios gestionar catálogo avanzado para este agente', verbose_name='Habilitar catálogo avanzado'),
        ),
        migrations.CreateModel(
            name='AdvancedCatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_catalog_products', to='agents.agentconfiguration', verbose_name='Configuración del agente')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='agents.advancedcatalogcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto de catálogo avanzado',
                'verbose_name_plural': 'Productos de catálogo avanzado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvancedCatalogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del modelo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='agents.advancedcatalogproduct', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Modelo de catálogo avanzado',
                'verbose_name_plural': 'Modelos de catálogo avanzado',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdvancedCatalogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('catalog', 'Imagen de catálogo'), ('price', 'Imagen de precio')], max_length=10, verbose_name='Tipo de imagen')),
                ('image', models.ImageField(upload_to='advanced_catalog/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.advancedcatalogmodel', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Imagen de catálogo avanzado',
                'verbose_name_plural': 'Imágenes de catálogo avanzado',
                'ordering': ['image_type', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='advancedcatalogcategory',
            name='agent_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_catalog_categories', to='agents.agentconfiguration', verbose_name='Configuración del agente'),
        ),
        migrations.AddIndex(
            model_name='advancedcatalogcategory',
            index=models.Index(fields=['agent_config'], name='agents_adva_agent_c_a6c2fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='advancedcatalogcategory',
            unique_together={('name', 'agent_config')},
        ),
    ]
